name: CI

on: [push]

jobs:
  build-win:
    runs-on: windows-latest    
    name: win-build-sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet build

  build-linux:
    runs-on: ubuntu-latest
    name: ubuntu-build-sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet build
